---
title: "R Notebook"
output: html_notebook
---


```{r}
library(tidyverse)
library(here)

weapons_crafting_clean <- read_csv(here("clean_data/weapons_crafting.csv"))
weapons_data_clean <- read_csv(here("clean_data/weapon_data.csv"))
```
```{r}
weapon_data_long %>% 
  filter(damage_type == "Na")
weapon_data_split
```


# Return materials
```{r}
weapons_crafting_clean %>% 
  filter(item == "Silver Sword") %>% 
  filter(upgrade_level == 1) %>% 
  select(material, amount_of_material) %>% 
  rename("Material" = material, "Amount of Material" = amount_of_material)
```
# Return Crafting Station
```{r}
weapons_crafting_clean %>% 
  filter(item == "Silver Sword") %>% 
  filter(upgrade_level == 1) %>% 
  distinct(crafting_station) %>% 
  pull() %>% 
  str_to_title()
```
# Return Crafting Station Level
```{r}
weapons_crafting_clean %>% 
  filter(item == "Silver Sword") %>% 
  filter(upgrade_level == 1) %>% 
  distinct(crafting_station_level) %>% 
  pull()
```
# Plot damage
```{r}
weapons_data_clean %>% 
  filter(name == "Silver Sword",
         min_max != "max") %>% 
  ggplot(aes(damage_type, values, fill = min_max)) +
  geom_col(show.legend = FALSE) +
  scale_fill_manual(values = c(
    "diff" = "green4",
    "min" = "green3"
  )) +
  theme_classic()+
  labs(
    x = "Damage Type",
    y = "Damage Values"
  ) +
  theme(
    axis.title = element_text(size = 12)
  )
```
```{r}
weapons_data_clean %>% 
  filter(name == "Silver Sword") %>% 
  mutate(min_max = case_when(
    str_detect(damage_type, "_min") ~ "min",
    str_detect(damage_type, "_max") ~ "max",
    str_detect(damage_type, "_diff") ~ "diff"
  ),
  damage_type = str_remove(damage_type, "_min|_max|_diff")
  ) %>% 
  mutate(min_max = coalesce(min_max, "min")) %>% 
  filter(min_max != "max")
```

```{r}
weapons_crafting_small <- weapons_crafting_clean %>% 
  select(item, type, material) %>% 
  distinct()

weapons_data_small <- weapons_data_clean %>% 
  select(name) %>% 
  distinct()

weapons_joined <- 
  full_join(weapons_crafting_small, weapons_data_small, by = join_by(item == name))

weapons_joined
```


```{r}
weapons_list <- distinct(weapons_data_clean, name)
weapons_crafting_list <- distinct(weapons_crafting_clean, item)

arrange(weapons_list, name)
arrange(weapons_crafting_list, item)
```




```{r}
weapon_data %>% 
  janitor::clean_names() %>% 
  mutate(
    # Extract damage type from damage column
    damage_type = str_to_lower(str_extract(damage, "[A-Z][a-z]+")),
    # Extract damage values
    damage = str_extract(damage, "[\\.0-9/]+"),
    # Same with dps
    dps_type = str_to_lower(str_extract(dps, "[A-Za-z]+")),
    dps = str_extract(dps, "[\\.0-9/]+"),
    # Remove x from backstab and convert to numeric
    backstab = as.numeric(str_remove(backstab, "x")),
    # convert to numeric
    stamina = as.numeric(stamina)
  ) %>% 
  mutate(
    # Rename total damage column
    max_total_damage = max_damage,
    
    # Separate min and max damage and dps
    min_dps = as.numeric(str_extract(dps, "[0-9]+")),
    max_dps = as.numeric(str_extract(dps, "[0-9\\.]+$")),
    
    min_damage = as.numeric(str_extract(damage, "[0-9]+")),
    max_damage = as.numeric(str_extract(damage, "[0-9\\.]+$")),
    
    # rename damage and dps types
    damage_type_max = paste0("damage_", damage_type, "_max"),
    damage_type_min = paste0("damage_", damage_type, "_min"),
    damage_type_diff = paste0("damage_", damage_type, "_diff"),
    
    dps_type_max = paste0("dps_", dps_type, "_max"),
    dps_type_min = paste0("dps_", dps_type, "_min"),
    dps_type_diff = paste0("dps_", dps_type, "_diff"),
    
    backstab_x10 = backstab * 10
    
  ) %>% 
  
  # add columns for the difference between min and max
  mutate(
         diff_dps = max_dps - min_dps,
         diff_damage = max_damage - min_damage
         ) %>% 

  select(-damage, -dps, -total_damage, -damage_type, -dps_type, -backstab)  
```

```{r}
weapon_type_list <- weapons_joined %>%
  filter(!type %in% c("upgrade", "tool", "shield", "magic", "weapon")) %>% 
  mutate(type = str_to_title(type)) %>% 
  distinct(type) %>% 
  pull() %>% 
  append("All")

weapons_joined %>%
  filter(material == "Wood")
```

```{r}

weapons_joined %>% 
  mutate(material = str_to_title(material)) %>% 
  filter(type == "bow") %>% 
  distinct(material) %>% 
  #arrange(material) %>% 
  pull() %>% 
  append("All") %>% 
  sort()
```

```{r}
type_input <- "All"
material_input <- "wood"

if(type_input == "All" & material_input == "All"){
  weapons_joined %>%
          distinct(item) %>%
          pull()
} else if (material_input != "All") {
   weapons_joined %>%
          filter(material == material_input) %>%
          distinct(item) %>%
          pull()
}
        
```

```{r}
type_input = "sword"
material_input = "blackmetal"

weapons_joined %>%
  {if(type_input != "all") filter(., type == type_input) else filter(., !is.na(type))} %>%
  {if(material_input != "all") filter(., material == material_input) else filter(., !is.na(type))} %>%
  distinct(item) %>%
  pull() %>% 
  sort()
```
