---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(here)
library(readxl)
library(janitor)
```

```{r}
armor <- clean_names(read_xlsx(here("raw_data/armour.xlsx")))
sets <- clean_names(read_xlsx(here("raw_data/armour.xlsx"), sheet = 2))
all_items <- clean_names(read_xlsx(here("raw_data/all_crafting.xlsx")))
```

```{r}
sets
```

```{r}
cleaned_armor <- all_items %>% 
  mutate(across(where(is.character), ~ str_to_lower(.x))) %>% 
  select(-c(description, set_bonus)) %>% 
  right_join(armor, by = join_by(item, upgrade_level)) %>% 
  left_join(sets) %>% 
  group_by(item, type, crafting_station_level, crafting_station, upgrade_level,
           armor, resistant, weak, set, weight, speed, other, bonus) %>% 
  summarise(materials = toString(unique(material)),
            material_amounts = toString(amount_of_material)) %>% 
  pivot_wider(names_from = crafting_station, values_from = crafting_station_level) %>% 
  clean_names()
```
```{r}
cleaned_armor %>% 
  filter(type == "cape" & upgrade_level == 1)
```



```{r}
armour %>% 
  filter(upgrade_level == 1) %>% 
  select(item, armor, weight)
```

```{r}
types <- all_items %>% 
  select(item, type) %>% 
  filter(type != "upgrade") %>% 
  distinct()

armour_type <- armour %>% 
  left_join(types)
```
```{r}
armour_type %>% 
  filter(type == "cape" & upgrade_level == 1) %>% 
  select(item, armor, weight, speed, resistant, weak)
```

```{r}
armor <- read_csv(here("clean_data/armor_data.csv"))
```
```{r}
armor %>% 
  rename("upgrade_level" = "Upgrade Level") %>% 
  filter(Type == "Chest" & upgrade_level == 1) %>% 
  select(Item, Armor, Weight, Speed, Resistant, Weak)
```
```{r}
names(armor)
```

```{r}
armor <- armor %>% 
  clean_names() %>% 
  mutate(across(where(is.character), ~ str_to_lower(.x)))

crafting_armor <- all_items %>% 
  semi_join(armor, join_by(item)) %>% 
  mutate(across(where(is.character), ~ str_to_lower(.x)))
```

```{r}
crafting_armor %>% 
  pivot_wider(names_from = crafting_station, values_from = crafting_station_level) %>% 
  clean_names() %>% 
  filter(is.na(workbench) | workbench <= 6) %>% 
  filter(is.na(forge) | forge <= 7) %>%
  filter(is.na(galdr_table) | galdr_table <= 0) %>%
  filter(is.na(black_forge) | black_forge <= 0)
```

```{r}
armor_list <- cleaned_armor %>% 
  filter(is.na(workbench) | workbench <= 4) %>% 
  filter(is.na(forge) | forge <= 2) %>%
  filter(is.na(galdr_table) | galdr_table <= 2) %>%
  filter(is.na(black_forge) | black_forge <= 2)
```
```{r}
chest_list <- cleaned_armor %>% 
  filter(type == "chest") %>% 
  select(item) %>% 
  pull()
```

```{r}
p <- armor_list %>% 
  filter(item %in% chest_list) %>%
  group_by(item) %>% 
  filter(upgrade_level == max(upgrade_level)) %>% 
  arrange(desc(armor)) %>% 
  head(5) %>% 
  select(item, upgrade_level, armor, weight) %>%
  pivot_longer(c(armor, weight), names_to = "stat", values_to = "value") %>% 
  mutate(item = str_to_title(item),
         stat = str_to_title(stat)) %>%
  unite("item", item:upgrade_level, sep = " - Level ",  remove = TRUE) %>% 
  ggplot(aes(item, value, fill = stat)) +
  geom_col(position = "dodge") +
  theme_classic() +
  theme(text = element_text(colour = "black"),
        axis.text = element_text(colour = "black"),
        legend.background = element_rect(fill = "transparent"),
        panel.background = element_rect(fill = "transparent"),
        panel.border = element_rect(fill = "transparent",
                                    colour = "transparent"),
        plot.background = element_rect(fill = "transparent",
                                       colour = NA),
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(
    x = "Chest",
    y = "Stat",
    fill = ""
  ) 
ggplotly(p)
```

```{r}
armor_list %>% 
  filter(item == "fenris coat" | item == "fenris leggings" |
           item == "fenris hood" | item == "wolf fur cape") %>%
  group_by(item) %>% 
  filter(upgrade_level == max(upgrade_level)) %>% 
  ungroup() %>% 
  select(item, upgrade_level, armor, weight, speed, resistant, weak, set) %>% 
  mutate(speed = coalesce(speed, 0)) %>% 
  mutate(speed = speed * 100) %>% 
  bind_rows(summarise(., across(where(is.numeric), sum),
                      across(where(is.character), ~""))
            ) %>% 
  mutate(across(where(is.character), str_to_title)) %>% 
  mutate(item = case_when(item == "" ~ "Total",
                          .default = item)) %>% 
  rename_all(stringr::str_to_title)
  
```
  
  